[database]
# uri = "mongodb://docker.for.mac.host.internal:27017/swapOrders"
uri = "mongodb://localhost/swapOrders"
debug = true

[application]
apiPort = 3030
swapExpirationDurationInSeconds = 3600
nodeSwapExpirationDurationInSeconds = 1800

[auth]
cookieSecret = '58da74ef560e5578cb46219b7818d7c2'
cookieMaxAgeMs = 86400000
simplePassword = '25ec02267950f537347b4a7c02b00ced'

[threshold]
manualAboveFromAmountUsd = 5000

# [vault]
# endpoint = "http://127.0.0.1:8200"
# mnemonicsBasePath = "secret/data/agent/mainnet/production/mnemonics"

[worker]
maxJobRetry = 5
jobRetryDelay = "5 seconds"
backendJobRetryDelay = "5 seconds"
minConcurrentSwaps = 3
defaultLockLifetimeInMs = 120000 # 2 min
killswitch = 'pm2 stop "Worker"'

[assets]
  [assets.BTC]
  network = "bitcoin_regtest"
  addressType = "bech32"
  swapMode = "p2wsh"
  feeNumberOfBlocks = 2
  blockTime = "5 seconds"
  defaultFee = "average"
    [assets.BTC.wallet]
    type = "js"
    mnemonic = "piece effort bind that embrace enrich remind powder sudden patient legend group"
    [assets.BTC.api]
    url = "http://localhost:3002/"
    [assets.BTC.batchApi]
    url = "http://localhost:9090/"
    [assets.BTC.rpc]
    url = "http://localhost:18443/"
    user = "admin1"
    password = "123"

  [assets.ETH]
  network="local"
  blockTime = "5 seconds"
  defaultFee = "average"
    [assets.ETH.wallet]
    type = "js"
    mnemonic = "piece effort bind that embrace enrich remind powder sudden patient legend group"
    [assets.ETH.scraper]
    url = "http://localhost:8080"
    [assets.ETH.rpc]
    url = "http://localhost:8545"

  [assets.DAI]
  network="local"
  type = "ERC20"
  blockTime = "5 seconds"
  contractAddress = "0x094cdd8e19b97505869c87a995a972c4df7f69a8"
  defaultFee = "average"
    [assets.DAI.wallet]
    type = "js"
    mnemonic = "piece effort bind that embrace enrich remind powder sudden patient legend group"
    [assets.DAI.scraper]
    url = "http://localhost:8080"
    [assets.DAI.rpc]
    url = "http://localhost:8545"

  [assets.RBTC]
  blockTime = "20 seconds"
  network = "rsk_testnet"
  defaultFee = "average"
  pegWith = "BTC"
    [assets.RBTC.rpc]
    url = "https://public-node.testnet.rsk.co"
    [assets.RBTC.scraper]
    url = "https://liquality.io/rsk-testnet-api/"
    [assets.RBTC.wallet]
    type = "js"
    mnemonic = "piece effort bind that embrace enrich remind powder sudden patient legend group"

  [assets.SOV]
  blockTime = "20 seconds"
  network = "rsk_testnet"
  defaultFee = "average"
  contractAddress = "0x6a9A07972D07E58f0daF5122D11e069288A375fB"
    [assets.SOV.rpc]
    url = "https://public-node.testnet.rsk.co"
    [assets.SOV.scraper]
    url="https://liquality.io/rsk-testnet-api/"
    [assets.SOV.wallet]
    type = "js"
    mnemonic = "piece effort bind that embrace enrich remind powder sudden patient legend group"
