name: Test, publish & deploy

on:
  push:
    tags:
      - v*

jobs:
  test_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 8
      - uses: actions/cache@v1
        env:
          node-version: 8
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-node${{ env.node-version }}-${{ hashFiles('**/package-lock.json') }}
      - run: cp sample.config.toml test.config.toml
      - run: docker-compose -f ./test/docker/docker-compose.yml up -d --build
      - run: sleep 30
      - run: npm ci
      - run: DEBUG=liquality:agent* npm test
      - run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > ~/.npmrc
      - run: npm publish --access public --tag next
        if: contains(github.ref, '-next.')
      - run: npm publish --access public
        if: contains(github.ref, '-next.') != true

  deploy:
    needs: test_publish
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        if: contains(github.ref, '-next.')
        with:
          host: ${{secrets.SSH_NEXT_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          port: 22
          script: ./update_reload_next
      - uses: appleboy/ssh-action@master
        if: contains(github.ref, '-next.') != true
        with:
          host: ${{secrets.SSH_NEXT_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          port: 22
          script: ./update_reload
